### ISSUE TITLE
Can't add the library in gradle

### ISSUE THREAD

**Issue by namooplus** [faradaj/BlurBehind#11]
When I try to add this library like this,

```
repositories {
mavenCentral()
    mavenLocal()
}

dependencies {
    compile 'com.faradaj:blur-behind:1.1.0'
}
```

"Dependency 'com.faradaj:blur-behind:1.1.0' not found"

How can i solve it? :worried:

p.s Run 'gradle install' on 'blur-behind' library project. <= What does it mean

**Comment by aswintyv** [comment]
+1

**Comment by aswintyv** [comment]
Look in the sample app file - https://github.com/faradaj/BlurBehind/blob/master/blur-behind-sample/build.gradle . I did as it's used there, and it seems to work fine.

**Comment by namooplus** [comment]
I'll try it thanks :)

**Comment by namooplus** [comment]
oh... now i can add the project but there is a strange error in library(blur-behind) AndroidManifest.xml

# Error
aapt: in generated file: String types not allowed (at 'versionCode' with value 'mVersionCode')

but there is no versionCode!! only
 ```
<manifest
        xmlns:android="http://schemas.android.com/apk/res/android"
        package="com.faradaj.blurbehind">

    <application/>

</manifest>
 ```
